// File: frontend/app/signals/page.tsx
import * as React from "react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Signals - QuantVision",
  description: "View and manage trading signals generated by our quantitative models",
};

export default function SignalsPage() {
  return (
    <main className="flex-1 p-4 sm:p-6 md:p-8">
        <div className="mx-auto max-w-7xl">
          <header className="mb-8">
            <h1 className="text-3xl font-bold tracking-tight text-text-primary">Signals</h1>
            <p className="mt-2 text-text-muted">
              View and manage trading signals generated by our quantitative models
            </p>
          </header>

          <div className="rounded-xl border border-divider bg-panel p-12 text-center">
            <div className="mx-auto max-w-md">
              <div className="mb-4 inline-flex h-16 w-16 items-center justify-center rounded-full bg-primary/20">
                <svg
                  className="h-8 w-8 text-primary"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                  aria-hidden="true"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M13 10V3L4 14h7v7l9-11h-7z"
                  />
                </svg>
              </div>
              <h2 className="text-xl font-semibold text-text-primary">Signals page coming soon</h2>
              <p className="mt-2 text-sm text-text-muted">
                This page is currently under development. Check back soon for trading signal features.
              </p>
            </div>
          </div>
        </div>
      </main>
  );
}

